/ Members
###
GET https://webexapis.com/v1/messages?roomId=Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vMDNkZTg5NTAtOTQyNS0xMWVkLWJjZDgtNDU1M2IyZDg3ZGYw
Content-Type: application/json
Authorization: Bearer YTMyNWViM2ItMmEyMC00MmY1LTg2OWUtZmQ5ZjU4MDY3YTRjYWFjYzE3ZGQtZWIy_P0A1_ff79c397-9d79-44f7-8296-8858b58f5ba8

###
POST https://webexapis.com/v1/messages
Content-Type: application/json
Authorization: Bearer YTMyNWViM2ItMmEyMC00MmY1LTg2OWUtZmQ5ZjU4MDY3YTRjYWFjYzE3ZGQtZWIy_P0A1_ff79c397-9d79-44f7-8296-8858b58f5ba8

{
  "roomId": "Y2lzY29zcGFyazovL3VybjpURUFNOnVzLXdlc3QtMl9yL1JPT00vNGRlOWM5NTAtOTk5NC0xMWVkLWE2MGYtN2QwZGVhZDgyZWMx",
  "text": "Hola desde Visual Studio Code de Jose Aguirre",
  "markdown": "Hola desde Visual Studio Code de Jose Aguirre"
}